name: Build Unreal Engine 5 Project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    env:
      UE_PROJECT_PATH: ${{ secrets.UE_PROJECT_PATH }}
      BUILD_OUTPUT_PATH: ${{ secrets.BUILD_OUTPUT_PATH }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      # Setup MSBuild
      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1.0.2

      # Build Unreal Project (Uses GitHub Secrets for paths)
      - name: Build UE5 Project
        run: |
          & "C:\Program Files\Epic Games\UE_5.3\Engine\Build\BatchFiles\RunUAT.bat" BuildCookRun `
            -project="$env:UE_PROJECT_PATH" `
            -noP4 -platform=Win64 -clientconfig=Development `
            -serverconfig=Development -cook -build -stage -pak `
            -archive -archivedirectory="$env:BUILD_OUTPUT_PATH"

      # Upload the build as an artifact
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: ${{ env.BUILD_OUTPUT_PATH }}
