name: Build Unreal Engine 5 Project
on:
  workflow_dispatch:
    inputs:
      platforms:
        description: 'Platforms to build for'
        required: true
        default: 'Windows,Linux,Mac'
        type: choice
        options:
          - 'Windows,Linux,Mac'
          - 'Windows'
          - 'Linux'
          - 'Mac'
          - 'Windows,Linux'
          - 'Windows,Mac'
          - 'Linux,Mac'

jobs:
  build-windows:
    runs-on: self-hosted
    if: contains(github.event.inputs.platforms, 'Windows')
    env:
      UE_PROJECT_PATH: ${{ secrets.UE_PROJECT_PATH }}
      BUILD_OUTPUT_PATH: ${{ github.workspace }}/build-output-windows
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true
      # Setup MSBuild
      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1.0.2
      # Build Unreal Project
      - name: Build UE5 Project for Windows
        run: |
          & "C:\Program Files\Epic Games\UE_5.5\Engine\Build\BatchFiles\RunUAT.bat" BuildCookRun `
            -project="$env:UE_PROJECT_PATH" `
            -noP4 -platform=Win64 -clientconfig=Development `
            -serverconfig=Development -cook -build -stage -pak `
            -archive -archivedirectory="$env:BUILD_OUTPUT_PATH"
        shell: powershell
      # Upload the build as an artifact
      - name: Upload Windows Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: ${{ github.workspace }}/build-output-windows
          retention-days: 7

  build-linux:
    runs-on: self-hosted
    if: contains(github.event.inputs.platforms, 'Linux')
    env:
      UE_PROJECT_PATH: ${{ secrets.UE_PROJECT_PATH }}
      BUILD_OUTPUT_PATH: ${{ github.workspace }}/build-output-linux
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true
      # Setup MSBuild (may be needed for some UE dependencies)
      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1.0.2
      # Build Unreal Project
      - name: Build UE5 Project for Linux
        run: |
          & "C:\Program Files\Epic Games\UE_5.5\Engine\Build\BatchFiles\RunUAT.bat" BuildCookRun `
            -project="$env:UE_PROJECT_PATH" `
            -noP4 -platform=Linux -clientconfig=Development `
            -serverconfig=Development -cook -build -stage -pak `
            -archive -archivedirectory="$env:BUILD_OUTPUT_PATH" `
            -targetplatform=Linux
        shell: powershell
      # Upload the build as an artifact
      - name: Upload Linux Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: ${{ github.workspace }}/build-output-linux
          retention-days: 7

  build-mac:
    runs-on: self-hosted
    if: contains(github.event.inputs.platforms, 'Mac')
    env:
      UE_PROJECT_PATH: ${{ secrets.UE_PROJECT_PATH }}
      BUILD_OUTPUT_PATH: ${{ github.workspace }}/build-output-mac
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true
      # Setup MSBuild (may be needed for some UE dependencies)
      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1.0.2
      # Build Unreal Project
      - name: Build UE5 Project for Mac
        run: |
          & "C:\Program Files\Epic Games\UE_5.5\Engine\Build\BatchFiles\RunUAT.bat" BuildCookRun `
            -project="$env:UE_PROJECT_PATH" `
            -noP4 -platform=Mac -clientconfig=Development `
            -serverconfig=Development -cook -build -stage -pak `
            -archive -archivedirectory="$env:BUILD_OUTPUT_PATH" `
            -targetplatform=Mac
        shell: powershell
      # Upload the build as an artifact
      - name: Upload Mac Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mac-build
          path: ${{ github.workspace }}/build-output-mac
          retention-days: 14
