name: Build Unreal Engine 5 Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: UE5 Build Project
        uses: OrchidIsle/UE5-Build-Project@0.3.0
        with:
          UPROJECT_PATH: "Aura.uproject"  # Change this to your actual project path
          BUILD_CONFIG: "Development"
          PLATFORM: "Win64"
          COOK: true
          STAGE: true
          PACKAGE: true
          ARCHIVE: true
          ARCHIVE_PATH: "PackagedBuild"

      - name: Upload Packaged Build
        uses: actions/upload-artifact@v4
        with:
          name: UnrealBuild
          path: PackagedBuild
