name: Build Unreal Engine 5 Project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest  # Using a Windows runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true  # Ensures submodules are pulled if needed

      - name: UE5 Build Project
        uses: OrchidIsle/UE5-Build-Project@0.3.0
        with:
          project_path: "Aura.uproject"
          build_platform: "Win64"
          build_configuration: "Development"
          package_project: true  # Enables packaging after building
          output_directory: "PackagedBuild"

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: UnrealBuild
          path: PackagedBuild
