name: Build Unreal Engine 5 Project - Windows

on:
  workflow_dispatch:
    inputs:
      configuration:
        description: 'Build configuration'
        required: true
        default: 'Development'
        type: choice
        options:
          - 'Development'
          - 'Shipping'
          - 'DebugGame'

jobs:
  build-windows:
    runs-on: self-hosted
    env:
      UE_PROJECT_PATH: ${{ secrets.UE_PROJECT_PATH }}
      BUILD_OUTPUT_PATH: ${{ github.workspace }}/build-output-windows
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Build UE5 Project for Windows
        run: |
          & "C:\Program Files\Epic Games\UE_5.5\Engine\Build\BatchFiles\RunUAT.bat" BuildCookRun `
            -project="$env:UE_PROJECT_PATH" `
            -noP4 -platform=Win64 -clientconfig=${{ github.event.inputs.configuration }} `
            -serverconfig=${{ github.event.inputs.configuration }} -cook -build -stage -pak `
            -archive -archivedirectory="$env:BUILD_OUTPUT_PATH"
        shell: powershell

      - name: Upload Windows Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-${{ github.event.inputs.configuration }}-build
          path: ${{ env.BUILD_OUTPUT_PATH }}
          retention-days: 7
